# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Plugin-HtmlTidy
version:      0.01
version_from: lib/CGI/Application/Plugin/HtmlTidy.pm
installdirs:  site
requires:
    CGI::Application:              3.21
    HTML::Tidy:                    1.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
