---
abstract: Add HTML::Tidy support to CGI::Application
author:
- Rhesa Rozendaal <rhesa@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.091260
license: perl
name: CGI-Application-Plugin-HtmlTidy
requires:
  CGI::Application: '4.01'
  HTML::Tidy: '1.08'
resources:
  repository: http://github.com/rhesa/cgi-application-plugin-htmltidy
version: '1.04'
